import { findMetadataPda, PublicKey } from '@metaplex-foundation/js'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import Minter from '../components/Minter'
import Header from '../components/Header'
import WalletContextProvider from '../contexts/WalletContextProvider'
import { useMetaplex } from '../hooks/useMetaplex'
import { motion } from 'framer-motion'

const Home: NextPage = () => {

  const metaplex = useMetaplex();
  const createCollection = async () => {
    const a = (
      await metaplex
        .nfts()
        .create({
          name: "My off-chain name",
          uri: "https://arweave.net/y5e5DJsiwH0s_ayfMwYk-SnrZtVZzHLQDSTZ5dNRUHA",
          sellerFeeBasisPoints: 250,
          isCollection: true,
        })
    ).nft;

    console.log('collection', a)

    const { nft } = await metaplex
      .nfts()
      .create({
        name: "My off-chain name",
        uri: "https://metadata.degods.com/g/9999.json",
        sellerFeeBasisPoints: 250,
        collection: findMetadataPda(a.mint.address),
      });

    console.log("TTTTT", nft)

  }
  useEffect(() => {

    // createCollection();

    // metaplex
    //   .nfts()
    //   .uploadMetadata({
    //     name: 'Collectionnn',
    //     description: "Collectionn",
    //     image: "https://lh3.googleusercontent.com/LTTv-eNP6d1bLtQB5yUEIMXBCNutzlCvOSoc3I6I-Nx2u8hYqiI4PPCZJWkKMqu-3LGKhkn0D9YTd3WyRekKg4vD4vLsHMqKpJEBjDbXrdNeWnj1RQ6dDysMlE01ggihXeu63zT5ap3_SeiioT4", //toMetaplexFile(arrayBuffer, data.image[0].name)
    //   }).then(({ uri }) => {
    //     // Mint NFT
    //     const nft = metaplex
    //       .nfts()
    //       .create({
    //         uri,
    //         name: '00000',
    //         sellerFeeBasisPoints: 10000,
    //         isCollection: true,
    //         collectionIsSized: true,
    //         collectionDetails: {
    //           V1: {
    //             size: 5
    //           }
    //         }
    //       }).then(data => console.log("Collection", data));

    //   });

    // metaplex
    //   .nfts()
    //   .uploadMetadata({
    //     name: '#0000',
    //     description: "NFT in Collection #00",
    //     image: "https://pbs.twimg.com/profile_images/1369019255128084483/DR2dCwjW_400x400.jpg", //toMetaplexFile(arrayBuffer, data.image[0].name)
    //     collection: {
    //       verified: false,
    //       key: new PublicKey('2PQRj2RDfsQnizJaRXbDhKYQFiy8ZSo68H6X2KKECwMq')
    //     }
    //   }).then(({ uri }) => {
    //     // Mint NFT
    //     const nft = metaplex
    //       .nfts()
    //       .create({
    //         uri,
    //         name: 'NFT01',
    //         sellerFeeBasisPoints: 10000,
    //         collection: new PublicKey('2PQRj2RDfsQnizJaRXbDhKYQFiy8ZSo68H6X2KKECwMq'),
    //       }).then(data => console.log("NFT", data));

    //   });


  }, [metaplex]);

  return (
    <div className='h-screen'>
      <Head>
        <title>NFT Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* Header */}
      <Header />

      {/* Main */}
      <main>

        {/* Minter */}
        <Minter />
        
      </main>

    </div>
  );
}

export default Home
